// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"os"
	"strings"

	"github.com/labstack/gommon/log"
    "github.com/alecthomas/template"
    "github.com/ghodss/yaml"
	"github.com/swaggo/swag"
)

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it.
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	const urlFileYaml string = "/docs/r2-back-openapi.yml"

	pwd, err := os.Getwd()
	if err != nil {
		return err.Error()
	}
	log.Info(pwd)

	doc, err := os.ReadFile(pwd + urlFileYaml)
	if err != nil {
		return err.Error()
	}

	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	js, err := yaml.YAMLToJSON([]byte(doc))
	if err != nil {
		return err.Error()
	}

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(string(js))
	if err != nil {
		return string(js)
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return string(doc)
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
